services:
  find_my_iphone_automate:
    container_name: find_my_iphone_automate
    image: ghcr.io/ridwan0110/find_my_iphone_automate:latest
    restart: unless-stopped
    volumes:
      - find_my_iphone_automate_data:/app/data
    environment:
      - TZ=
      # Normally configured via the .env file
      - MASTER_PASSWORD
      - APPLE_ID
      - APPLE_ID_PASSWORD
      - TARGET_DEVICE_MODEL
      - ALERT_METHOD
      - WHATSAPP_RECIPIENTS
      - DISCORD_WEBHOOK
      - POLL_INTERVAL_SECONDS
volumes:
  find_my_iphone_automate_data:
    driver: local
